import { ReduxState, EarthquakeSliceInitialState } from "./redux-interfaces";
import {
  Earthquake,
  EarthquakeTableProps,
  EarthquakeRowProps,
  ApiEarthquake,
  ApiEarthquakeFeature,
  ApiEarthquakeFeatureProperties,
  ApiEarthquakeMetadata,
  ApiEarthquakeDetail,
  ApiEarthquakeDetailGeometry,
  ApiEarthquakeDetailOrigin,
  ApiEarthquakeDetailOriginPhaseDataContents,
  ApiEarthquakeDetailOriginPhaseDataContentsContentsXML,
  ApiEarthquakeDetailOriginPhaseDataQuakeML,
  ApiEarthquakeDetailOriginProperties,
  ApiEarthquakeDetailPhaseData,
  ApiEarthquakeDetailPhaseDataProperties,
  ApiEarthquakeDetailProducts,
  ApiEarthquakeDetailProperties,
} from "./earthquake-interfaces";

export type {
  ReduxState,
  EarthquakeSliceInitialState,
  Earthquake,
  EarthquakeTableProps,
  EarthquakeRowProps,
  ApiEarthquake,
  ApiEarthquakeFeature,
  ApiEarthquakeFeatureProperties,
  ApiEarthquakeMetadata,
  ApiEarthquakeDetail,
  ApiEarthquakeDetailGeometry,
  ApiEarthquakeDetailOrigin,
  ApiEarthquakeDetailOriginPhaseDataContents,
  ApiEarthquakeDetailOriginPhaseDataContentsContentsXML,
  ApiEarthquakeDetailOriginPhaseDataQuakeML,
  ApiEarthquakeDetailOriginProperties,
  ApiEarthquakeDetailPhaseData,
  ApiEarthquakeDetailPhaseDataProperties,
  ApiEarthquakeDetailProducts,
  ApiEarthquakeDetailProperties,
};
